<a href="https://colab.research.google.com/github/PJlohiya/PPS-Assignment-No.11/blob/main/Assignment_No_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello World")

Hello World


In [2]:
import numpy as np
a=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(a)

#horizontal slicing
print(b[:])
print(b[0:2])
print(b[1:3])
print(b[2:3])

#vertical slicing
print(b[:,0:2])
print(b[:,2:3])
print(b[0:2,0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [7 8 9]]
[[7 8 9]]
[[1 2]
 [4 5]
 [7 8]]
[[3]
 [6]
 [9]]
[[1 2]
 [4 5]]
